apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAzyqb+BQK0wpNWWZnfpFS4ugwiNStySMXk9Qd3gx1kQhqnDDtAvBBQUGAu4jH/lpM5CLH81LvFLUvXbG3EFiHPhxkcXa30R5y18WI4AWpPnd/nZswa2J+PEawxo8ftwbkbxR55jfWAL/EpV8RfJ5QBWZsrdSkyrtEDSQlJuji188XNjJgq0rHPfGAApaFFkT5QWJucEAG5nqpW/mq32gzL7veTINCtK5Lzgn0Zv4x2G32hdnMvRiCjvoxKpJqk/PyE5oLAvBQ/gc8ugDyBG/mI8dABuNeV6Uq1LwZl0WJ897MHseuMi8KZbZuH+4CYFuXHVXLIcjBTF/1u712JA3Ggn5Uvrkwy3sAaYzsyESE4HgcypGd5lQT5X8w2071enknNpMzHW9IJih4JF9OmyYKx5mmHAlZ7dXY=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-git-repo
      namespace: default

