apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: a-k2
  project: defaultproject
spec:
  active: true
  cluster:
    name: c1-mks
  config:
    concurrency: 30
    environment:
      numWorkers: 5
    kubernetes:
      limits:
        cpu: "1"
        memory: 1Gi
  type: Cluster
  version: r3.7.0
