apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: a-k2
  project: defaultproject
spec:
  active: true
  cluster:
    name: c1-mks
  config:
    concurrency: 55
    environment:
      numWorkers: 25
    kubernetes:
      limits:
        cpu: "2"
        memory: 2Gi
  type: Cluster
  version: r4.0.0
