apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: a-k3
  project: defaultproject
spec:
  active: true
  cluster:
    name: c1-mks
  config:
    concurrency: 60
    environment:
      numWorkers: 60
  type: Cluster
  version: r4.0.0
