apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: agent-k8s
  project: defaultproject
spec:
  cluster:
    name: c1-mks
  config:
    concurrency: 50
    environment:
      numWorkers: 10
    kubernetes:
      limits:
        cpu: "250"
        memory: 1Gi
  type: Cluster
  version: r3.7.0
