apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: agent-d2
  project: defaultproject
spec:
  active: true
  config:
    concurrency: 50
    docker:
      limits:
        cpu: "1"
        memory: 1Gi
    environment:
      numWorkers: 20
  type: Docker
  version: r4.0.1
