apiVersion: gitops.k8smgmt.io/v3
kind: Agent
metadata:
  name: k8s-agent
  project: defaultproject
spec:
  cluster:
    name: my-cluster
  config:
    concurrency: 55
    environment:
      numWorkers: 15
    kubernetes:
      limits:
        cpu: 255m
        memory: 2Gi
  type: Cluster
  version: r3.7.0
