apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-helm-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQA7qIoMLUvMBnB/AFyHnsxTOe1yarYxzh7ouQmh6tIQ51qEYhv2OHilWRH0nHv715zWoXapavBD7gpvQsEZq3L6EyuEyiw7kWSe66HkjDiIazBjIU3r8hx1pr4VXi8ftQWGViXlAVkwBl3hORNsGp0x7FTYg6TZJqIRINUGr0zyh1IKJ/BXtyFphMi/tjLx0PMOVVPRFQADbAreTUQK7Aovzw21Wk4YrysYEuWv8P6ybM/0XAQjPg8fO7BZ+D8U/fuN/BY8Rm9HD0n2Nog1aGxYbsC6WEQddUYM0RQyHxBBP/mTz19pk5Z67i5A/K0OAF3bWbWLYN8Ycxq1EcOYrcPBLFizCKHZ8WXr/zRDeG6736pFHcc4p1SHe3Q=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-helm-repo
      namespace: default

