apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQA5auTZ/9xHuIwd+wyDlT27KYDZ/GxugKb7Jgn9hAXC2b3YNilcNmSPRvWzkfw7pH4xzyWQ+y65JN6DVAzrc2BhOmH7jQTViuGkdR/9kUHaTXmToQcQp895FoC8Dz0BYIaWlgVXZtfOqnPfVB1hFrC86yVQj80eoYldPrsLj728Uipa/RQCTfiUOht3ljwl75ysItustvVWVQXe6x6MZAHWTNVI+VwadFpAQIds1uPnwL+HEA1pWMx+FMmrlaSRAidirW57GNzMnpJJV9UzGgLEFr54SkaCtoDj429YakuhpaA2OXlXsoareXL5jRemRxL6hsEQqEK7BBzSrARNE5lOglKlIFFvDbz0SnumKKzPT1sJhDIxFQE7nRwd4GrCHUg4UkGVPBYREMgcbwn5GuPYqi5PcFOy4yACoULyPq4DSuq+e9R/x4DV+CcKLvwlJZDz4E2+/A0IWCWkdPXK3QDSm1D0nb+K3sDw7945UQ==
  template:
    metadata:
      creationTimestamp: null
      name: akshay-repo
      namespace: default

