apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAEQV7XDugTb9XvBo6OKEg8fYianMqLtULF3XAjjytdeR00TVDuo6tj7Z0vE7MFBfEjU4Zt+6I0oslwkRiZssF8fc+dVXdKQzP+wXLA70e7wmQPPtCjlYP4FXTMHNQ75gj/0vk2y87rHY421vZcJk6Bfxs+jMHOj4pu01/wKQ4hccIovYPirnh+g5ZPYTzMOu1PodUiG3tkZQ8lmXkpNjzeHNymzWBdZjT8FIsu07yIHPGcgqudfQJ4gdNx26/UitAazfENCHbfFMvgGwvbweQ64TZkQsGEATtYiAhsSmQ4nqX4O+GC4ypCXPLP5XEyzEqKRe/LsBEuYd5C0g4zVikQBWVIxIhdbzkvJxIkQLVteeC75sTnjDdb1RsBNuAjhG/68a/X20g7V/WTBmA+8lB2qA+/uagWt1+eajWhCDJLsnK8c4+ntCAhbSGKNSHt034aoF8Gcn6k1GpVdoGO7Lkb8DvwkORXFJwQYbP8Kw==
  template:
    metadata:
      creationTimestamp: null
      name: akshay-repo
      namespace: default

