apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-helm-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCnpGEs7niMlK+nOnzIL8KLUcNXA++j34MgiVJ3fCn4GUlPsR4/5bG9eTIuSeBvPArOWiadpaKB22xv7xJsSvP5oIaw+EK0pfUhw/4FQeP0NW+F2lR5+mtsGwHuuZ2vMCS6pEdIw5agIiPzYJ58pKuPdGa2/8RtJyLOxrRd4cNnydvoW1pUS5eDqFlB3x/HfQ41DG6D+TBp+HUPJP5us7yn3mvJLbh4Wm8Dn7ZioaaJrjdB0pM2Tt02iQ/wJyfxMhNGdhO4g7Fm4nPRsPulX93woLr4aFQjMxd4S2x0emDpOKm8jug0ixUekoGh3fAqXyvXFR01+UlE09d67uOr8Q6+UfA3QXN8xF+eYG2U32o6Jfd5FEMaDt9gzaA=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-helm-repo
      namespace: default

