apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-git-p
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCYIeKju5npT8fRKXTAvfz3qaIUU2fg0jujIdtZrgkNli3ZazWh/ayGy64i65+UpaGFCnesoLpiGp4u0bipO1mvnunQ5ZmBbwZL/2EqF82++LHWv8D/1NHUkkYUvY8Zd6v5txm9+CsPZ2FsOyVvPuFp8HQ2lrxPCbzzCV06Zu869qb/bm5T02WD2paTTApc3XQq5eqzqLUgcN84CRUqjYHBEA0L3CHtvwlePgBWmz8ASdO38oc7N9rAE9TsfJdlcpD7FA7EyO/KvojuYdIXM15YMdp6USo5j7MxFrQ+GOcjr91YJIesXNWFDzhhnkCBmAWcNNBxSD4tlMhlqVGOYsyCraoSGQEyQkqjQC/oAGIYKNl5o6j0mEJCvVSk5arq6tHojpO2qXg3xqbXhJblM/wdZ4fYgG97t7A=
  template:
    metadata:
      creationTimestamp: null
      name: akshay-git-p
      namespace: default

