apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAEQEsofwrHnjceYP4hx15k6+tiKRuI3XWUHJ3YZbgaBhyjMb9/Umh+V4tJQ5R4qypdCF4T/r70Nm171hzjrpjkfMa70mflqd4Ih4+U1fRLYrbUt8kiunJ4jHdXcRIqFZlX4zu/3fjNZNpadVZ+oe9luBpmeZ8vrZdKXkeFkkVLUC8BeykXOKkmmWsShFEhAUfplYMDAKRR60UZdPVibGtMA6ffsMaNAgI4jZ2NIipLPDSvAlwUORrPRLy4A9/vaTu6Y7o/fdqqUz9eIvzOuoKvI7XaVJVilJKitEcAIlWQIX3JP5PkV/CTcjrfe70XzyGwIDi2AYLF/iH2fiG7AEdLU+gckXUXrVaRDaRcdB3t07SJRfM4bSB6DoM91pf/hhQm5zJo9GHy2iF1eQuZOOHA5v/Ba5xEfjU=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-git-repo
      namespace: default

