apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-git-p
  namespace: default
spec:
  encryptedData:
    credentials.password: AQB1LTZbpBn5Ha9V68dIvdlP5WgOUmrTi203ANiqczdI8LCfWwuNqwyWXGNYssvkZbo7HP214y0NqBCRZeo37VesW3SlTBFcdjKnQW+C/YwaIw0gfC7hMqNSnSSGC6R7thdO8KIAyNobgJAVNOYMQaKKC8kf+OUNp/pEnabRXRvgeQxw7l2TBjyCA4Nu268Z3940l7S9Ul8FrmkPLJx4QAGqztucbHyl7YXTxBOc+Az3+G2LPGgpUQKWsQqEwf4LiDlXMa7t29rMMip8du6p8Cv1m58DglQ+YNx6x1GfCZjV5HNKY8BV6WudeTVRNPlj6ISWpYHCA/VoDOekezo3n5JC+xjv+vBO7WEpdYpGhtorGV6MUGnT3+yvNbtPDbytPSoLmNG1rhnBSqBDm6n1u8mamrifTlMCZ2g=
  template:
    metadata:
      creationTimestamp: null
      name: akshay-git-p
      namespace: default

