apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: akshay-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBeFlogvyJIL3wGbKNTern/abVySb11ogRQkuY4Mm/HjwsVBhlC/8grehYqh+0RaPJ5+RZP841K3BC0DYCpOPQRVPD7uDP3FkO1oAQEEDcOpb3YbnUgFNDX4leYWbpOnLJPNL8PeKlQwiwPs4Ol9/dyaVTtBiq7r4ssr+JIHhXRkzCvw05NAphvP7W00iQStdBhAPjCxv8zc0JhbrzgK8uAWMtV7TMTG233DNGl4omJ8+5l/BzS+L507JQDHpCuu8ZKhgaKnld2z7TYY4XfqKOcTRE2f1XcJNbjoR2NsIY0rSkZ7FQ65XMQm/9ncUx1AtqXM5JCTds+W7+UD3GjN9fZJSRUxbZcjHEE8IWzOva4MScrjsaSV5kJ7PplbyDYAQ7VVTKtI17qXGwe8s0SFofWGvcVLP19Rmlt6+PwX3e3zDSX/HFpsehp0rnx6HAxp1dQMrDQjrulMaoxgn+xKrfiFAHhCdczY27cyB1zpA==
  template:
    metadata:
      creationTimestamp: null
      name: akshay-repo
      namespace: default

